---
title: "Testing script"
author: "prodigy_systems_and_services"
date: "27/03/2020"
output: html_document
vignette: >
  %\VignetteIndexEntry{Testing script}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
library(tidyverse); library(dplyr); library(sf); library(leaflet)
```

```{r master_dataset}

master <- st_read(system.file("extdata","mi_master_polygons.shp", package = "TBDfun"))
head(master)
```

```{r tract, warning=FALSE}
tract <- master %>%
  group_by(NAME) %>%
  summarize(population = sum(estimate, na.rm = TRUE))

tract_map <- leaflet(tract) %>% addPolygons() %>% addTiles()
print(tract_map)
```

```{r county, warning=FALSE}
county <- master %>%
  group_by(county) %>%
  summarize(population = sum(estimate, na.rm = TRUE))

county_map <- leaflet(county) %>% addPolygons() %>% addTiles()
print(county_map)
```


```{r cmhsp, warning=FALSE}
cmhsp <- master %>%
  group_by(CMHSP) %>%
  summarize(population = sum(estimate, na.rm = TRUE))

cmhsp_map <- leaflet(cmhsp) %>% addPolygons() %>% addTiles()
print(cmhsp_map)
```



```{r pihp, warning=FALSE}
pihp <- master %>%
  group_by(PIHP) %>%
  summarize(
    population = sum(estimate, na.rm = TRUE))

pihp_map <- leaflet(pihp) %>% addPolygons() %>% addTiles()
print(pihp_map)
```



```{r agency, warning=FALSE}
agency <- master %>%
  group_by(agency) %>%
  summarize(
    population = sum(estimate, na.rm = TRUE))

agency_map <- leaflet(agency) %>% addPolygons() %>% addTiles()
print(agency_map)
```
